"""Top-level package for `medrap_analysis`."""

from .comorbidity import (
    CHARLSON_CATEGORIES,
    assign_patient_charlson,
    load_charlson_lookup,
    lookup_categories,
)
from .demographic_analysis import (
    DocKeywordProvider,
    LDATopicProvider,
    StaticMappingProvider,
    TitleKeywordProvider,
    aggregate_race,
    bin_age,
    build_comorbidity_keyword_table,
    build_keyword_demographic_table,
    build_patient_demographic_frame,
    build_pearson_residual_table,
    extract_val_schema,
    load_subject_demographics,
    render_demographic_heatmaps,
    write_residual_csv,
)
from .llm_judge import (
    FakeJudge,
    Judge,
    JudgePair,
    JudgePromptBuilder,
    OpenAIJudge,
    PatientTimelineRenderer,
    Verdict,
    build_human_validation_subset,
    build_pairs,
    build_per_patient_rollup,
    compute_patient_clinical_summary,
    run_judge,
    summarize_winrates,
    write_results_workbook,
)

__all__ = [
    "CHARLSON_CATEGORIES",
    "DocKeywordProvider",
    "FakeJudge",
    "Judge",
    "JudgePair",
    "JudgePromptBuilder",
    "LDATopicProvider",
    "OpenAIJudge",
    "PatientTimelineRenderer",
    "StaticMappingProvider",
    "TitleKeywordProvider",
    "Verdict",
    "aggregate_race",
    "assign_patient_charlson",
    "bin_age",
    "build_comorbidity_keyword_table",
    "build_human_validation_subset",
    "build_keyword_demographic_table",
    "build_pairs",
    "build_patient_demographic_frame",
    "build_pearson_residual_table",
    "build_per_patient_rollup",
    "compute_patient_clinical_summary",
    "extract_val_schema",
    "load_charlson_lookup",
    "load_subject_demographics",
    "lookup_categories",
    "render_demographic_heatmaps",
    "run_judge",
    "summarize_winrates",
    "write_residual_csv",
    "write_results_workbook",
]
